### ISSUE TITLE
New Updates issue | Can not launch the game

### ISSUE THREAD

**Issue by mxKeaton** [mim1q/ConvenientDecor#10]
[2024-03-18-3.log](https://github.com/mim1q/ConvenientDecor/files/14638482/2024-03-18-3.log)

After Updating I can not start the game anymore. It references the chung manager, but even after removing it, it jumps to another mod and provides the same issue. Just downgrading fixed it. Log provided

**Comment by mim1q** [comment]
Are you 100% sure it's Convenient Decor that's causing this?
The error in the log doesn't mention the mod. It only mentions c2me and entity_texture_features from what I could see. I'll investigate some more what's going on here tho 👍

Edit: checked this out and yep! Convenient Decor seems to be at fault here. Weird, but I'm going to try and figure out why it happens 🤔

**Comment by mim1q** [comment]
Oh! And have you changed anything in the config?

**Comment by mim1q** [comment]
Fixed! 
https://modrinth.com/mod/convenient-decor/version/0.4.1

**Comment by mxKeaton** [comment]
That was quick! Thank you!
