### ISSUE TITLE
[Crash On Startup] 1.20.1 Fabric

### ISSUE THREAD

**Issue by Fyoncle** [mim1q/ConvenientDecor#15]
With the 0.4.1 of the convenient decor, with no logs being provided or either errors, game just breaks up, i experienced this error in the Eternal Realms modpack and didn't try the mod standalone, so it may be a compatibility issue between any mod Eternal Realms modpack contains

**Comment by mim1q** [comment]
Is Eternal Realms available on Modrinth or CurseForge, and does it come with Convenient Decor preinstalled, or did you add it yourself? Just for the record, I do not support nor approve my mods being used in modpacks outside the two sites mentioned before, so I can't help much if that's the case. It's okay if you added it yourself tho!

Unfortunately I cannot do anything about this issue without the crash log. After you launch the game and it crashes, a `latest.log` file should be created in your `.minecraft/logs` folder, can you provide that?

**Comment by Fyoncle** [comment]
> Is Eternal Realms available on Modrinth or CurseForge, and does it come with Convenient Decor preinstalled, or did you add it yourself? Just for the record, I do not support nor approve my mods being used in modpacks outside the two sites mentioned before, so I can't help much if that's the case. It's okay if you added it yourself tho!
> 
> Unfortunately I cannot do anything about this issue without the crash log. After you launch the game and it crashes, a `latest.log` file should be created in your `.minecraft/logs` folder, can you provide that?

It's in Modrinth, and it was gonna be added for the next release of Eternal Realms, but it crashed, heres the log https://mclo.gs/3oJ8L5B

**Comment by mim1q** [comment]
Got it! Yeah, I really don't see anything in the log, it really does seem like a random crash...
Are you sure it is caused by Convenient Decor? Would be great if you could check if it crashes (and maybe produces a proper log) in these cases:

1. the modpack without Convenient Decor
2. only Convenient Decor with its dependencies
3. the whole pack on another PC (if you have a way to test this. If not, I might check it out myself in the next few days, since the previous release of the pack is on Modrinth)

One last random question - do you have Turkish as your system language? There's a bug that makes the game crash in that case, but I'll be releasing a bugfix update soon 😅

**Comment by Fyoncle** [comment]
> Got it! Yeah, I really don't see anything in the log, it really does seem like a random crash... Are you sure it is caused by Convenient Decor? Would be great if you could check if it crashes (and maybe produces a proper log) in these cases:
> 
> 1. the modpack without Convenient Decor
> 2. only Convenient Decor with its dependencies
> 3. the whole pack on another PC (if you have a way to test this. If not, I might check it out myself in the next few days, since the previous release of the pack is on Modrinth)
> 
> One last random question - do you have Turkish as your system language? There's a bug that makes the game crash in that case, but I'll be releasing a bugfix update soon 😅

1. It doesn't crash without Convenient Decor
2. It got all the Dependencies installed
3. Also crashes on another PC
(note: yes i have turkish.)

**Comment by mim1q** [comment]
Most likely the Turkish bug, then. Expect a little bugfix update today or tomorrow. 
I'll post the link here, too, so you can verify if that fixes it 👍

**Comment by Fyoncle** [comment]
> Most likely the Turkish bug, then. Expect a little bugfix update today or tomorrow. I'll post the link here, too, so you can verify if that fixes it 👍

You're amazing ❤️ Big respect!

**Comment by mim1q** [comment]
https://modrinth.com/mod/convenient-decor/version/0.4.2 😁

**Comment by Fyoncle** [comment]
> https://modrinth.com/mod/convenient-decor/version/0.4.2 😁

Thanks, lemme test it ❤️

**Comment by Fyoncle** [comment]
It works! Thank you for your instant fix about this, much respect!

**Comment by Poopooracoocoo** [comment]
Fixed by https://github.com/mim1q/ConvenientDecor/commit/1211f0fb7d09df6330e66de10a17909c0c8b5c82
